
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACKET = 6;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int EQUAL = 7;
  public static final int NUMBER = 4;
  public static final int MINUS = 3;
  public static final int OBRACKET = 5;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "NUMBER",
  "OBRACKET",
  "CBRACKET",
  "EQUAL"
  };
}

